(function(){
  const props = Array.isArray(window.NFL_PROPS) ? window.NFL_PROPS : [];
  const systems = Array.isArray(window.NFL_SYSTEMS) ? window.NFL_SYSTEMS : [];
  const games = Array.isArray(window.NFL_GAMES) ? window.NFL_GAMES : [];
  const winTrends = Array.isArray(window.NFL_WIN_TRENDS) ? window.NFL_WIN_TRENDS : [];
  const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const pct = (a,b) => b ? `${(a/b*100).toFixed(1)}%` : '—';
  const group = (rows,key) => rows.reduce((out,row)=>{const value=row[key]||'OTHER';(out[value] ||= []).push(row);return out;},{});
  const graded = props.filter(p=>['HIT','MISS'].includes(p.result));
  const hits = graded.filter(p=>p.result==='HIT').length;
  const styleGroups = group(graded,'style');
  const environmentGroups = group(graded,'environment');
  const systemGroups = group(systems,'previousWeekResults');
  let propFilters = {search:'', style:'ALL', environment:'ALL', result:'ALL'};
  let systemFilters = {situation:'ALL', outcome:'ALL', week:'ALL'};
  const backbone = () => window.NFL_BACKBONE || null;

  function topGroups(groups, limit=6){
    return Object.entries(groups).map(([name,rows])=>({name, rows, hits:rows.filter(r=>r.result==='HIT').length})).sort((a,b)=>b.rows.length-a.rows.length).slice(0,limit);
  }
  function consumerSummary(){
    if(!games.length) return 'No current-week NFL card has been entered yet. The historical database is active, so consumers can research which prop styles and game environments have performed best without mistaking old results for a current recommendation.';
    const game=games[0];
    return `${game.mainReason || 'The matchup and historical evidence point in the same direction.'} The biggest risk is ${(game.biggestRisk || 'late injury, weather, or line movement').toLowerCase()}. Overall, ${game.bestBet || 'the listed play'} is the clearest opportunity currently supported by the database.`;
  }
  function renderOverview(){
    const db = backbone();
    const canonical = db?.canonical || {};
    const reference = db?.reference || {};
    const hotTrends = Array.isArray(db?.hotTrends) ? db.hotTrends : [];
    const hotProps = Array.isArray(db?.hotProps) ? db.hotProps : [];
    const current = games.length ? games.map(g=>`<article class="nfl-opportunity-card"><div><span class="tag">Current Opportunity</span><h3>${esc(g.awayTeam)} @ ${esc(g.homeTeam)}</h3><strong>${esc(g.bestBet)}</strong></div><p>${esc(g.mainReason)}</p></article>`).join('') : `<article class="nfl-empty-current"><span class="tag gray">Week Board</span><h3>Current-week matchups will live here.</h3><p>The NFL backbone is now separated from the legacy research sheets. The next release will feed verified schedules and game logs into this board automatically.</p></article>`;
    const trendHtml = hotTrends.length ? hotTrends.slice(0,4).map(t=>`<article class="nfl-hot-card"><div><span>${esc(t.team_abbr)} • ${esc(t.market)}</span><b>${esc(t.sample_label)}</b></div><strong>${Number(t.hit_rate).toFixed(1)}%</strong><h3>${esc(t.environment)}</h3><small>${t.games} games • since ${t.trend_start_year} • strength ${Number(t.strength_score).toFixed(1)}</small></article>`).join('') : '<article class="nfl-empty-current"><h3>Reference trends loading</h3></article>';
    const propHtml = hotProps.length ? hotProps.slice(0,4).map(p=>`<article class="nfl-hot-card prop"><div><span>${esc(p.player_name)} • ${esc(p.market_style)}</span><b>${esc(p.sample_label)}</b></div><strong>${Number(p.hit_rate).toFixed(1)}%</strong><h3>${p.hits}-${p.misses}</h3><small>${p.games} tracked lines • ${esc(p.team_abbr || '')}</small></article>`).join('') : '<article class="nfl-empty-current"><h3>Prop profiles loading</h3></article>';
    document.querySelector('#nflOverview').innerHTML = `
      <section class="nfl-backbone-banner"><div><p class="eyebrow">NFL Intelligence Backbone</p><h2>${db ? 'Connected to Supabase' : 'Loading verified NFL data'}</h2></div><div class="nfl-backbone-stats"><span><strong>${canonical.teams ?? 32}</strong> Teams</span><span><strong>${canonical.games ?? 0}</strong> Canonical Games</span><span><strong>${reference.winTrends ?? winTrends.length}</strong> Seed Trends</span><span><strong>${reference.propObservations ?? props.length}</strong> Prop Rows</span></div></section>
      <div class="section-head compact-head"><div><p class="eyebrow">Hottest Team Trends</p><h2>Signals worth opening first</h2></div></div>
      <section class="nfl-hot-grid">${trendHtml}</section>
      <div class="section-head compact-head"><div><p class="eyebrow">Hottest Prop Profiles</p><h2>Historical player profiles</h2></div></div>
      <section class="nfl-hot-grid">${propHtml}</section>
      <section class="nfl-two-column"><div><div class="section-head compact-head"><div><p class="eyebrow">This Week</p><h2>NFL Matchups</h2></div></div>${current}</div>
      <div><div class="section-head compact-head"><div><p class="eyebrow">Foundation Status</p><h2>What is verified now</h2></div></div><div class="nfl-signal-list"><article><span>Canonical data</span><strong>${canonical.games ? 'ACTIVE' : 'READY FOR INGESTION'}</strong><small>Games, quarter scores, player stats and markets have dedicated tables.</small></article><article><span>Owner research</span><strong>${reference.winTrends ?? winTrends.length} trends</strong><small>Preserved as reference evidence, not treated as canonical game truth.</small></article><article><span>Quality control</span><strong>${db?.qualityIssues ?? 0} review flags</strong><small>Ambiguous source rows are flagged instead of silently corrected.</small></article></div></div></section>`;
  }
  function renderProps(){
    const styles=['ALL',...Object.keys(styleGroups).sort()];
    const envs=['ALL',...Object.keys(environmentGroups).sort()];
    const rows=props.filter(p=>(propFilters.style==='ALL'||p.style===propFilters.style)&&(propFilters.environment==='ALL'||p.environment===propFilters.environment)&&(propFilters.result==='ALL'||p.result===propFilters.result)&&(!propFilters.search||`${p.player} ${p.team} ${p.opponent} ${p.bet}`.toLowerCase().includes(propFilters.search.toLowerCase())));
    document.querySelector('#nflPropLab').innerHTML=`<div class="section-head"><div><p class="eyebrow">Player Intelligence</p><h2>NFL Prop Lab</h2><p>Filter the historical prop database without mixing it into MLB data.</p></div></div>
    <div class="nfl-filter-bar"><input id="nflPropSearch" placeholder="Search player, team, opponent..." value="${esc(propFilters.search)}"><select id="nflPropStyle">${styles.map(x=>`<option ${x===propFilters.style?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="nflPropEnvironment">${envs.map(x=>`<option ${x===propFilters.environment?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="nflPropResult">${['ALL','HIT','MISS'].map(x=>`<option ${x===propFilters.result?'selected':''}>${x}</option>`).join('')}</select></div>
    <p class="count">Showing ${rows.length} of ${props.length} historical props.</p><div class="nfl-table-wrap"><table><thead><tr><th>Week</th><th>Player / Bet</th><th>Matchup</th><th>Environment</th><th>Style</th><th>Result</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${p.week}</td><td><strong>${esc(p.player)}</strong><small>${esc(p.bet.replace(p.player,''))}</small></td><td>${esc(p.team)} ${esc(p.opponent)}</td><td>${esc(p.environment)}</td><td>${esc(p.style)}</td><td><span class="nfl-result ${p.result.toLowerCase()}">${p.result}</span></td></tr>`).join('')}</tbody></table></div>`;
    ['nflPropSearch','nflPropStyle','nflPropEnvironment','nflPropResult'].forEach(id=>document.getElementById(id)?.addEventListener('input',e=>{const map={nflPropSearch:'search',nflPropStyle:'style',nflPropEnvironment:'environment',nflPropResult:'result'};propFilters[map[id]]=e.target.value;renderProps();}));
  }
  function renderSystems(){
    const situations=['ALL',...Object.keys(systemGroups).sort()];
    const outcomes=['ALL',...new Set(systems.map(s=>s.outcome))].sort();
    const weeks=['ALL',...new Set(systems.map(s=>String(s.week)))].sort((a,b)=>Number(a)-Number(b));
    const rows=systems.filter(s=>(systemFilters.situation==='ALL'||s.previousWeekResults===systemFilters.situation)&&(systemFilters.outcome==='ALL'||s.outcome===systemFilters.outcome)&&(systemFilters.week==='ALL'||String(s.week)===systemFilters.week));
    const trendCards = winTrends.slice().sort((a,b)=>b.hitRate-a.hitRate).map(t=>`<article><span>${esc(t.teamName)} • ${esc(t.market)}</span><strong>${Number(t.hitRate).toFixed(1)}%</strong><small>${esc(t.environment)} • ${t.games} GP • since ${t.trendStartYear}</small></article>`).join('');
    document.querySelector('#nflSystemLab').innerHTML=`<div class="section-head"><div><p class="eyebrow">Historical Situations</p><h2>NFL System Lab</h2><p>Win trends and qualifying systems are stored separately so hit-rate evidence is never confused with ungraded qualification rows.</p></div></div><h3>Verified Win-Trend Samples</h3><div class="nfl-system-cards">${trendCards || '<article><span>No win trends loaded</span><strong>—</strong></article>'}</div><div class="nfl-filter-bar"><select id="nflSystemSituation">${situations.map(x=>`<option ${x===systemFilters.situation?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="nflSystemOutcome">${outcomes.map(x=>`<option ${x===systemFilters.outcome?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="nflSystemWeek">${weeks.map(x=>`<option ${x===systemFilters.week?'selected':''}>${esc(x)}</option>`).join('')}</select></div><p class="count">Showing ${rows.length} of ${systems.length} system rows.</p><div class="nfl-system-cards">${Object.entries(group(rows,'previousWeekResults')).map(([name,items])=>`<article><span>${esc(name)}</span><strong>${items.length}</strong><small>qualifying records shown</small></article>`).join('')}</div><div class="nfl-table-wrap"><table><thead><tr><th>Week</th><th>Previous Week</th><th>Matchup</th><th>Recorded Angle</th><th>Line</th><th>Context</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${s.week}</td><td>${esc(s.previousWeekResults)}</td><td>${esc(s.awayTeam)} @ ${esc(s.homeTeam)}</td><td>${esc(s.outcome)}</td><td>${esc(s.line)}</td><td>${esc(s.environment)}</td></tr>`).join('')}</tbody></table></div>`;
    ['nflSystemSituation','nflSystemOutcome','nflSystemWeek'].forEach(id=>document.getElementById(id)?.addEventListener('input',e=>{const map={nflSystemSituation:'situation',nflSystemOutcome:'outcome',nflSystemWeek:'week'};systemFilters[map[id]]=e.target.value;renderSystems();}));
  }
  function renderPerformance(){
    const styleHtml=Object.entries(styleGroups).map(([name,rows])=>{const h=rows.filter(r=>r.result==='HIT').length;return `<article><span>${esc(name)}</span><strong>${h}-${rows.length-h}</strong><small>${pct(h,rows.length)} • ${rows.length} plays</small></article>`}).sort().join('');
    const envHtml=topGroups(environmentGroups,12).map(x=>`<article><span>${esc(x.name)}</span><strong>${x.hits}-${x.rows.length-x.hits}</strong><small>${pct(x.hits,x.rows.length)} • ${x.rows.length} plays</small></article>`).join('');
    document.querySelector('#nflPerformance').innerHTML=`<div class="section-head"><div><p class="eyebrow">Transparent Results</p><h2>NFL Performance</h2><p>Historical props are graded exactly as supplied. System rows remain counts only because their result column was not included.</p></div></div><div class="nfl-performance-hero"><article><span>Overall</span><strong>${hits}-${graded.length-hits}</strong><small>${pct(hits,graded.length)} hit rate</small></article><article><span>Tracked</span><strong>${graded.length}</strong><small>graded historical props</small></article><article><span>Systems</span><strong>${systems.length}</strong><small>qualification rows, not graded bets</small></article><article><span>Win Trends</span><strong>${winTrends.length}</strong><small>team-market environment samples</small></article></div><h3>By Prop Style</h3><div class="nfl-system-cards">${styleHtml}</div><h3>By Environment</h3><div class="nfl-system-cards">${envHtml}</div>`;
  }
  function renderGuide(){document.querySelector('#nflDataGuide').innerHTML=`<div class="section-head"><div><p class="eyebrow">Foolproof Updates</p><h2>Where NFL updates go</h2><p>Every NFL data type has one home. MLB files never need to be opened for an NFL update.</p></div></div><div class="nfl-guide-grid"><article><span>Historical Props</span><code>sports/nfl/data/nfl-props.js</code><p>Add completed player-prop records.</p></article><article><span>Historical Systems</span><code>sports/nfl/data/nfl-systems.js</code><p>Add qualifying game situations.</p></article><article><span>Win Trends</span><code>sports/nfl/data/nfl-win-trends.js</code><p>Add team, market, environment, hit rate, sample size, and start year.</p></article><article><span>Current Weekly Card</span><code>sports/nfl/data/nfl-games.js</code><p>Add only verified current opportunities and evidence.</p></article><article><span>NFL Display Logic</span><code>sports/nfl/nfl-app.js</code><p>Controls filters, summaries, and rendering.</p></article></div>`;}
  function init(){if(!document.querySelector('#sport-nfl'))return;renderOverview();renderProps();renderSystems();renderPerformance();renderGuide();window.addEventListener('sports-edge:nfl-backbone-ready',()=>{renderOverview();renderSystems();});document.querySelectorAll('.nfl-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nfl-tab').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.nfl-view').forEach(x=>x.classList.toggle('active',x.dataset.nflPanel===btn.dataset.nflView));}));document.querySelectorAll('.nfl-scroll').forEach(btn=>btn.addEventListener('click',()=>document.getElementById(btn.dataset.target)?.scrollIntoView({behavior:'smooth'})));}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
