function createHttpError(message,statusCode=500,details=null){const e=new Error(message);e.statusCode=statusCode;e.details=details;return e;}
function setCommonHeaders(response){response.setHeader('Content-Type','application/json; charset=utf-8');response.setHeader('Cache-Control','no-store, max-age=0');response.setHeader('X-Content-Type-Options','nosniff');}
function sendJson(response,statusCode,payload){setCommonHeaders(response);return response.status(statusCode).json(payload);}
function sendSuccess(response,payload={},statusCode=200){return sendJson(response,statusCode,{ok:true,...payload});}
function sendError(response,error){const statusCode=Number.isInteger(error?.statusCode)&&error.statusCode>=400&&error.statusCode<=599?error.statusCode:500;if(statusCode>=500)console.error('Sports Edge MLB API error:',error);return sendJson(response,statusCode,{ok:false,error:error?.message||String(error||'Unknown server error.'),details:statusCode<500?error?.details:undefined});}
function requireMethod(request,allowed){const list=(Array.isArray(allowed)?allowed:[allowed]).map(v=>String(v).toUpperCase());const actual=String(request?.method||'').toUpperCase();if(!list.includes(actual))throw createHttpError(`Method ${actual||'UNKNOWN'} is not allowed.`,405,{allowedMethods:list});return actual;}
function parseJsonBody(request){const body=request?.body;if(body===undefined||body===null||body==='')return{};if(typeof body==='object'&&!Buffer.isBuffer(body))return body;try{return JSON.parse(Buffer.isBuffer(body)?body.toString('utf8'):String(body));}catch{throw createHttpError('Request body must contain valid JSON.',400);}}
async function readJson(request){return parseJsonBody(request);}
function requireBoolean(value,name,defaultValue=false){if(value===undefined||value===null||value==='')return defaultValue;if(typeof value==='boolean')return value;const normalized=String(value).toLowerCase();if(normalized==='true')return true;if(normalized==='false')return false;throw createHttpError(`${name} must be true or false.`,400);}
function requireInteger(value,name,{defaultValue=null,minimum=null,maximum=null}={}){if(value===undefined||value===null||value==='')return defaultValue;const parsed=Number(value);if(!Number.isInteger(parsed))throw createHttpError(`${name} must be an integer.`,400);if(minimum!==null&&parsed<minimum)throw createHttpError(`${name} must be at least ${minimum}.`,400);if(maximum!==null&&parsed>maximum)throw createHttpError(`${name} must be no greater than ${maximum}.`,400);return parsed;}
function handleOptions(request,response){if(String(request?.method||'').toUpperCase()!=='OPTIONS')return false;response.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');response.setHeader('Access-Control-Allow-Headers','Content-Type,x-sports-edge-admin-token');response.status(204).end();return true;}
export{createHttpError,handleOptions,parseJsonBody,readJson,requireBoolean,requireInteger,requireMethod,sendError,sendError as handleError,sendJson,sendSuccess,setCommonHeaders};
