import { callRpc } from './supabase.js';
import { getSchedule, getGame } from './stats-api-client.js';
import { transformGame } from './transform.js';
const ISO=/^\d{4}-\d{2}-\d{2}$/; const DAY=86400000; const MAX_IMPORT_DAYS=7;
function httpError(message,statusCode){const e=new Error(message);e.statusCode=statusCode;return e;}
function validateImportRange(startDate,endDate){if(!ISO.test(startDate||'')||!ISO.test(endDate||''))throw httpError('startDate and endDate must use YYYY-MM-DD.',400);const start=new Date(`${startDate}T00:00:00Z`),end=new Date(`${endDate}T00:00:00Z`);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||start>end)throw httpError('Invalid import date range.',400);const dayCount=Math.floor((end-start)/DAY)+1;if(dayCount>MAX_IMPORT_DAYS)throw httpError(`Imports are currently limited to ${MAX_IMPORT_DAYS} calendar days per request.`,400);return{dayCount};}
function extractScheduleGames(payload){const map=new Map();for(const date of payload?.dates||[])for(const game of date?.games||[]){const id=Number(game?.gamePk);if(Number.isInteger(id)&&id>0)map.set(id,game);}return[...map.values()];}
async function mapWithConcurrency(items,concurrency,worker){const results=new Array(items.length);let cursor=0;async function run(){while(cursor<items.length){const index=cursor++;results[index]=await worker(items[index],index);}}await Promise.all(Array.from({length:Math.max(1,Math.min(concurrency||3,items.length||1))},run));return results;}
async function importDateRange({startDate,endDate,dryRun=false,concurrency=3}){const range=validateImportRange(startDate,endDate);const counters={discovered:0,attempted:0,inserted:0,updated:0,failed:0,dryRun:0};const errors=[];const runId=dryRun?null:await callRpc('sports_edge_mlb_start_import',{p_start_date:startDate,p_end_date:endDate,p_dry_run:false});try{const games=extractScheduleGames(await getSchedule({startDate,endDate}));counters.discovered=games.length;await mapWithConcurrency(games,concurrency,async game=>{counters.attempted+=1;try{const payload=transformGame(game,await getGame(game.gamePk));if(dryRun){counters.dryRun+=1;return;}const action=await callRpc('sports_edge_mlb_upsert_game',{p_payload:payload});if(String(action).toLowerCase()==='inserted')counters.inserted+=1;else counters.updated+=1;}catch(error){counters.failed+=1;const item={gamePk:Number(game?.gamePk)||null,message:error.message};errors.push(item);if(runId)await callRpc('sports_edge_mlb_log_error',{p_import_run_id:runId,p_game_pk:item.gamePk,p_stage:'GAME_IMPORT',p_error_message:item.message,p_details:item}).catch(()=>{});}});const status=counters.failed===0?'SUCCESS':counters.failed===counters.discovered?'FAILED':'PARTIAL';if(runId)await callRpc('sports_edge_mlb_finish_import',{p_import_run_id:runId,p_status:status,p_discovered:counters.discovered,p_inserted:counters.inserted,p_updated:counters.updated,p_failed:counters.failed,p_message:counters.failed?`${counters.failed} game import(s) failed.`:null,p_audit:{requestedDays:range.dayCount,attempted:counters.attempted,errors}});return{runId,startDate,endDate,dayCount:range.dayCount,dryRun,status,counters,errors};}catch(error){if(runId)await callRpc('sports_edge_mlb_finish_import',{p_import_run_id:runId,p_status:'FAILED',p_discovered:counters.discovered,p_inserted:counters.inserted,p_updated:counters.updated,p_failed:counters.failed,p_message:error.message,p_audit:{errors}}).catch(()=>{});throw error;}}
export{extractScheduleGames,importDateRange,mapWithConcurrency,validateImportRange};
