const DEFAULT_TIMEOUT_MS=20000; const DEFAULT_ATTEMPTS=3;
function supabaseError(message,statusCode=502,details=null){const e=new Error(message);e.statusCode=statusCode;e.details=details;return e;}
function configuration(){const url=String(process.env.SUPABASE_SECRET_KEY ||
process.env.SUPABASE_SERVICE_ROLE_KEY||'').trim().replace(/\/+$/,'');const key=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'').trim();if(!url||!key)throw supabaseError('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be configured in Vercel.',503);const parsed=new URL(url);if(parsed.protocol!=='https:')throw supabaseError('SUPABASE_URL must use HTTPS.',503);return{url,key};}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function requestSupabase(path,{method='GET',body,timeoutMs=DEFAULT_TIMEOUT_MS,attempts=DEFAULT_ATTEMPTS}={}){const{url,key}=configuration();let last;for(let attempt=1;attempt<=attempts;attempt+=1){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(`${url}${path}`,{method,signal:controller.signal,headers:{apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();let payload=null;try{payload=text?JSON.parse(text):null;}catch{payload=text;}if(!response.ok)throw supabaseError(`Supabase request failed (${response.status}): ${payload?.message||payload?.details||payload||'Unknown error'}`,response.status>=500?502:response.status,payload);return payload;}catch(error){last=error;const retryable=error?.name==='AbortError'||!error?.statusCode||Number(error.statusCode)>=500;if(!retryable||attempt===attempts)break;await sleep(500*attempt);}finally{clearTimeout(timer);}}if(last?.name==='AbortError')throw supabaseError(`Supabase request timed out after ${timeoutMs} milliseconds.`,504);throw last||supabaseError('Unknown Supabase request failure.',502);}
function validateRpcName(name){const value=String(name||'').trim();if(!/^[a-z][a-z0-9_]*$/i.test(value))throw supabaseError('Supabase RPC function name is invalid.',500);return value;}
async function callRpc(name,body={},options={}){if(!body||Array.isArray(body)||typeof body!=='object')throw supabaseError('RPC body must be an object.',500);return requestSupabase(`/rest/v1/rpc/${encodeURIComponent(validateRpcName(name))}`,{method:'POST',body,...options});}
async function checkDatabaseHealth(){const started=Date.now();const database=await callRpc('sports_edge_mlb_status',{});return{ok:true,latencyMs:Date.now()-started,database};}
export{callRpc,checkDatabaseHealth,configuration,requestSupabase,supabaseError as createSupabaseError,validateRpcName};
